(function() {var implementors = {};
implementors["pwbox"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/struct.ErasedPwBox.html\" title=\"struct pwbox::ErasedPwBox\">ErasedPwBox</a>",synthetic:false,types:["pwbox::erased::ErasedPwBox"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/struct.CipherOutput.html\" title=\"struct pwbox::CipherOutput\">CipherOutput</a>",synthetic:false,types:["pwbox::traits::CipherOutput"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/struct.SensitiveData.html\" title=\"struct pwbox::SensitiveData\">SensitiveData</a>",synthetic:false,types:["pwbox::utils::SensitiveData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/rcrypto/struct.Scrypt.html\" title=\"struct pwbox::rcrypto::Scrypt\">Scrypt</a>",synthetic:false,types:["pwbox::rcrypto::Scrypt"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/rcrypto/struct.Aes128Gcm.html\" title=\"struct pwbox::rcrypto::Aes128Gcm\">Aes128Gcm</a>",synthetic:false,types:["pwbox::rcrypto::Aes128Gcm"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/sodium/struct.Scrypt.html\" title=\"struct pwbox::sodium::Scrypt\">Scrypt</a>",synthetic:false,types:["pwbox::sodium::Scrypt"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"pwbox/sodium/struct.XSalsa20Poly1305.html\" title=\"struct pwbox::sodium::XSalsa20Poly1305\">XSalsa20Poly1305</a>",synthetic:false,types:["pwbox::sodium::XSalsa20Poly1305"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
